version: '3.3'

services:

  mongo-db:
    image: mongo:latest
    container_name: mongo_database
    ports:
      - 27017:27017
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo-db:27017/?authSource=admin
      # - ME_CONFIG_BASICAUTH_USERNAME=admin
      # - ME_CONFIG_BASICAUTH_PASSWORD=pass
    links:
      - mongo-db
    ports:
      - "8081:8081"
    depends_on:
      - mongo-db
    networks:
      - mongodb_network


networks:
  mongodb_network:
